"""add columns for bulk upload redesign

Revision ID: 755992d1fcc0
Revises: 0001_initial
Create Date: 2026-06-25 05:37:23.595751

"""
from alembic import op
import sqlalchemy as sa


revision = '755992d1fcc0'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('domain', table_name='domains')
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=True)
    op.add_column('emails', sa.Column('job_id', sa.String(length=100), nullable=True))
    op.drop_index('email', table_name='emails')
    op.drop_index('ix_emails_status', table_name='emails')
    op.create_index(op.f('ix_emails_email'), 'emails', ['email'], unique=True)
    op.create_index(op.f('ix_emails_job_id'), 'emails', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('current_stage', sa.String(length=20), nullable=False))
    op.add_column('jobs', sa.Column('progress_percent', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('estimated_time_remaining', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('error_details', sa.JSON(), nullable=True))
    op.drop_index('job_id', table_name='jobs')
    op.drop_index('ix_jobs_job_id', table_name='jobs')
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.create_index('ix_jobs_job_id', 'jobs', ['job_id'], unique=False)
    op.create_index('job_id', 'jobs', ['job_id'], unique=True)
    op.drop_column('jobs', 'error_details')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'estimated_time_remaining')
    op.drop_column('jobs', 'progress_percent')
    op.drop_column('jobs', 'current_stage')
    op.drop_index(op.f('ix_emails_job_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_email'), table_name='emails')
    op.create_index('ix_emails_status', 'emails', ['status'], unique=False)
    op.create_index('email', 'emails', ['email'], unique=True)
    op.drop_column('emails', 'job_id')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.create_index('domain', 'domains', ['domain'], unique=True)
    # ### end Alembic commands ###
