"""add columns for job stages and email job_id

Revision ID: d0739350dd1a
Revises: 755992d1fcc0
Create Date: 2026-06-25 05:39:00.899274

"""
from alembic import op
import sqlalchemy as sa


revision = 'd0739350dd1a'
down_revision = '755992d1fcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
