"""add force_fresh column to jobs table

Revision ID: fb0e8ed1bc40
Revises: add_spf_dmarc_columns
Create Date: 2026-07-24 13:32:59.618836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = 'fb0e8ed1bc40'
down_revision = 'add_spf_dmarc_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_keys_key_prefix', table_name='api_keys')
    op.drop_index('key_hash', table_name='api_keys')
    op.create_unique_constraint(None, 'api_keys', ['key_prefix'])
    op.add_column('jobs', sa.Column('force_fresh', sa.Boolean(), nullable=False))
    op.alter_column('smtp_retry_queue', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('smtp_retry_queue', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_retry_email', table_name='smtp_retry_queue')
    op.create_index(op.f('ix_smtp_retry_queue_email'), 'smtp_retry_queue', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smtp_retry_queue_email'), table_name='smtp_retry_queue')
    op.create_index('idx_retry_email', 'smtp_retry_queue', ['email'], unique=False)
    op.alter_column('smtp_retry_queue', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('smtp_retry_queue', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('jobs', 'force_fresh')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_index('key_hash', 'api_keys', ['key_hash'], unique=True)
    op.create_index('ix_api_keys_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    # ### end Alembic commands ###
